services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basic_microservice_db
    ports:
      - "5433:5432"

  web_app:
    container_name: web_app
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DB_NAME: basic_microservice_db
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8003:8000"
