"""add is_banned

Revision ID: 4405a7ce29ce
Revises: 333fbd434611
Create Date: 2024-08-20 00:18:45.692653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4405a7ce29ce'
down_revision: Union[str, None] = '333fbd434611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'is_banned')
    # ### end Alembic commands ###
