"""add confirm email

Revision ID: 761c47e3d330
Revises: 4405a7ce29ce
Create Date: 2024-08-20 19:03:19.304812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761c47e3d330'
down_revision: Union[str, None] = '4405a7ce29ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'is_confirmed')
    # ### end Alembic commands ###
